language: node_js
node_js:
  - 6
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - npm install
script:
 # - $(npm bin)/cypress run --record
  
 - cypress run --record --key aa8279f3-afd5-4aca-829d-18ed7a2ccf9f
